FROM golang:1.16.3
WORKDIR /app

RUN go install github.com/golang/mock/mockgen@v1.6.0
RUN go install github.com/githubnemo/CompileDaemon@v1.3.0
RUN go install github.com/mna/pigeon@v1.1.0

COPY ./go.mod ./go.sum ./
RUN go mod download
COPY . .
EXPOSE 8080
